using System.Collections.Generic;
using System.Globalization;
using System.Text;

using FastEnum.Extensions.Generator.Specs;
using FastEnum.Extensions.Generator.Utils;

using Microsoft.CodeAnalysis.Text;

using static FastEnum.Extensions.Generator.EnumExtensionsGenerator;

namespace FastEnum.Extensions.Generator.Emitters;

internal abstract partial class SourceEmitter
{
    private const string FileHeader =
"""
// <auto-generated/>

#if NETCOREAPP3_0_OR_GREATER
#nullable enable annotations
#nullable disable warnings
#endif

""";

    protected readonly Framework _framework;
    protected readonly EnumSourceGenerationContext _sourceGenerationContext;
    protected readonly List<EnumGenerationSpec> _generationSpec;

    protected EnumGenerationSpec _currentSpec;

    public SourceEmitter(in EnumSourceGenerationContext sourceGenerationContext, List<EnumGenerationSpec> generationSpec, Framework framework)
    {
        _framework = framework;
        _sourceGenerationContext = sourceGenerationContext;
        _generationSpec = generationSpec;
    }

    /// <summary>
    /// Emits a framewrok specifiy implementation of TryParse
    /// </summary>
    /// <returns>The generated TryParse implementation (one ore more methods)</returns>
    public void Emit()
    {
        foreach (EnumGenerationSpec enumGenerationSpec in _generationSpec)
        {
            _currentSpec = enumGenerationSpec;

            StringBuilder sb = StringBuilderPool.Get();

            AddFileAndClassHeader(sb);
            AddFieldsAndGetMethods(sb);
            AddToString(sb);
            AddToStringFormatDoc(sb);
            AddToStringFormat(sb);
            AddIsDefined(sb);
            AddPrivateHelperMethods(sb);
            CloseClassAndNamespace(sb);

            string generatedClass = StringBuilderPool.Return(sb);

            // Add extension implementation.
            AddSource($"{_currentSpec.Name}Extensions.g.cs", generatedClass);
        }
    }

    private void AddFileAndClassHeader(StringBuilder sb)
    {
        sb.AppendLine(FileHeader);

        if (!_currentSpec.IsGlobalNamespace)
        {
            sb
                .Append("namespace ")
                .AppendLine(_currentSpec.Namespace)
                .AppendLine("{");
        }

        string classHeaderIndent = Get(Indentation.Class);

        sb
            .Append(classHeaderIndent).AppendLine("/// <summary>")
            .Append(classHeaderIndent).Append("/// Extension methods for <see cref=\"")
            .Append(_currentSpec.CommentCompatibleFullName).AppendLine("\" />")
            .Append(classHeaderIndent).AppendLine("/// </summary>")
            .Append(classHeaderIndent)
                .Append("[global::System.CodeDom.Compiler.GeneratedCode(\"FastEnum.Extensions.Generator.EnumToStringGenerator\", \"")
                .Append(Assembly.Version).AppendLine("\")]")
            .Append(classHeaderIndent).Append(_currentSpec.Modifier).Append(" static class ").Append(_currentSpec.Name).AppendLine("Extensions")
            .Append(classHeaderIndent).AppendLine("{");
    }

    private void AddFieldsAndGetMethods(StringBuilder sb)
    {
        // we are nested in a generic class, therefore we are unable to emit these fields
        if (_currentSpec.GenericTypeParameters.Length == 0)
        {
            string methodIndent = Get(Indentation.Method);
            string methodBodyIndent = Get(Indentation.MethodBody);

            sb
                .Append(methodIndent).Append("private static readonly ").Append(_currentSpec.UnderlyingType).AppendLine("[] _underlyingValues =")
                .Append(methodIndent).AppendLine("{");

            foreach (EnumMemberSpec member in _currentSpec.Members)
            {
                sb.Append(methodBodyIndent).Append(member.Value).AppendLine(",");
            }

            sb
                .Append(methodIndent).AppendLine("};")
                .AppendLine()
                .Append(methodIndent).Append("private static readonly ").Append(_currentSpec.FullName).AppendLine("[] _values =")
                .Append(methodIndent).AppendLine("{");

            foreach (EnumMemberSpec member in _currentSpec.Members)
            {
                sb.Append(methodBodyIndent).Append(_currentSpec.FullName).Append('.').Append(member.Name).AppendLine(",");
            }

            sb
                .Append(methodIndent).AppendLine("};")
                .AppendLine()
                .Append(methodIndent).AppendLine("private static readonly global::System.String[] _names =")
                .Append(methodIndent).AppendLine("{");

            foreach (EnumMemberSpec member in _currentSpec.Members)
            {
                sb.Append(methodBodyIndent).Append("nameof(")
                    .Append(_currentSpec.FullName).Append('.').Append(member.Name)
                    .AppendLine("),");
            }

            sb.Append(methodIndent).AppendLine("};")
                .AppendLine();
        }

        sb.Append("""
        /// <summary>
        /// The number of members in the enum.
        /// </summary>
        public const global::System.Int32 MembersCount = 
""").Append(_currentSpec.Members.Count).AppendLine(";").AppendLine();

        if (_currentSpec.GenericTypeParameters.Length != 0)
        {
            return;
        }

        sb.AppendFormat(CultureInfo.InvariantCulture, """
        /// <summary>
        /// Retrieves an array of the values of the members defined in <see cref="{0}" />.
        /// </summary>
        /// <returns>An array of the values defined in <see cref="{0}" />.</returns>
        public static {1}[] GetValues() => _values;

        /// <summary>
        /// Retrieves an array of the underlying vales of the members defined in <see cref="{0}" />.
        /// </summary>
        /// <returns>An array of the underlying values defined in <see cref="{0}" />.</returns>
        public static {2}[] GetUnderlyingValues() => _underlyingValues;

        /// <summary>
        /// Retrieves an array of the names of the members defined in <see cref="{0}" />.
        /// </summary>
        /// <returns>An array of the names of the members defined in <see cref="{0}" />.</returns>
        public static global::System.String[] GetNames() => _names;

""", _currentSpec.CommentCompatibleFullName, _currentSpec.FullName, _currentSpec.UnderlyingType)
            .AppendLine();
    }

    private void AddToString(StringBuilder sb)
    {
        string methodIndent = Get(Indentation.Method);
        string methodBodyIndent = Get(Indentation.MethodBody);
        string nesting1Indent = Get(Indentation.Nesting1);

        sb
            .Append(methodIndent).AppendLine("/// <summary>")
            .Append(methodIndent).AppendLine("/// Converts the value of this instance to its equivalent string representation.")
            .Append(methodIndent).AppendLine("/// </summary>")
            .Append(methodIndent).AppendLine("/// <returns>The string representation of the value of this instance.</returns>")
            .Append(methodIndent).Append(_currentSpec.Modifier).Append(" static global::System.String FastToString").Append(_currentSpec.GenericTypeParameters)
            .Append("(this ").Append(_currentSpec.FullName).Append(" value)").AppendLine(_currentSpec.GenericTypeConstraints)
            .Append(methodIndent).AppendLine("{")
            .Append(methodBodyIndent).AppendLine("switch (value)")
            .Append(methodBodyIndent).AppendLine("{");

        foreach (EnumMemberSpec member in _currentSpec.Members)
        {
            sb.Append(nesting1Indent).Append("case ").Append(_currentSpec.FullName).Append('.').Append(member.Name)
                .Append(": return nameof(").Append(_currentSpec.FullName).Append('.').Append(member.Name).AppendLine(");");
        }

        sb.Append(nesting1Indent).Append("default: return (");

        AddCast(sb, _currentSpec.FullName, _currentSpec.UnderlyingType)
            .AppendLine(").ToString();");

        sb
            .Append(methodBodyIndent)
            .AppendLine("}")
            .Append(methodIndent)
            .AppendLine("}")
            .AppendLine();
    }

    private void AddToStringFormatDoc(StringBuilder sb)
    {
        string methodIndent = Get(Indentation.Method);

        sb
           .Append(methodIndent).AppendLine("/// <summary>")
           .Append(methodIndent).AppendLine("/// Converts the value of this instance to its equivalent string representation using the specified format.")
           .Append(methodIndent).AppendLine("/// </summary>")
           .Append(methodIndent).AppendLine("/// <param name=\"format\"> A format string.</param>")
           .Append(methodIndent).AppendLine("/// <returns>The string representation of the value of this instance as specified by format.</returns>")
           .Append(methodIndent).AppendLine("/// <exception cref=\"global::System.FormatException\"><paramref name=\"format\"/> contains an invalid specification.</exception>");
    }

    protected abstract void AddToStringFormat(StringBuilder sb);

    private void AddIsDefined(StringBuilder sb)
    {
        string methodIndent = Get(Indentation.Method);
        string methodBodyIndent = Get(Indentation.MethodBody);
        string nesting1Indent = Get(Indentation.Nesting1);
        string nesting2Indent = Get(Indentation.Nesting2);

        sb
            .Append(methodIndent).AppendLine("/// <summary>")
            .Append(methodIndent).AppendLine("/// Returns a <see langword=\"bool\"/> telling whether the given enum value exists in the enumeration.")
            .Append(methodIndent).AppendLine("/// </summary>")
            .Append(methodIndent).AppendLine("/// <param name=\"value\">The value to check if it's defined</param>")
            .Append(methodIndent).AppendLine("/// <returns><see langword=\"true\"/> if the value exists in the enumeration, <see langword=\"false\"/> otherwise</returns>")
            .Append(methodIndent).Append("public static global::System.Boolean IsDefined(this ").Append(_currentSpec.FullName).AppendLine(" value)")
            .Append(methodIndent).AppendLine("{")
            .Append(methodBodyIndent).AppendLine("switch (value)")
            .Append(methodBodyIndent).AppendLine("{");

        foreach (EnumMemberSpec member in _currentSpec.Members)
        {
            sb.Append(nesting1Indent).Append("case ").Append(_currentSpec.FullName).Append('.').Append(member.Name).AppendLine(":");
        }


        sb
            .Append(nesting2Indent).AppendLine("return true;")
            .Append(nesting1Indent).AppendLine("default:")
            .Append(nesting2Indent).AppendLine("return false;")
            .Append(methodBodyIndent).AppendLine("}")
            .Append(methodIndent).AppendLine("}")
            .AppendLine();
    }

    protected abstract void AddTryParseString(StringBuilder sb);

    protected abstract void AddFormatNumberAsHexBufferGeneration(StringBuilder sb);

    protected abstract void AddToCharsBufferDefinition(StringBuilder sb);

    private void AddPrivateHelperMethods(StringBuilder sb)
    {
        string methodIndent = Get(Indentation.Method);
        string methodBodyIndent = Get(Indentation.MethodBody);
        string nesting1Indent = Get(Indentation.Nesting1);
        string nesting2Indent = Get(Indentation.Nesting2);

        sb
            .Append(methodIndent).AppendLine("/// <summary>")
            .Append(methodIndent).AppendLine("/// Formats the data for the underlying value as hex into a new, fixed-length string.")
            .Append(methodIndent).AppendLine("/// </summary>")
            .Append(methodIndent).AppendLine("[global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]")
            .Append(methodIndent)
                .Append("private static global::System.String FormatNumberAsHex(")
                .Append(_currentSpec.FullName)
                .AppendLine(" data)")
            .Append(methodIndent).AppendLine("{");

        AddFormatNumberAsHexBufferGeneration(sb);

        int startIndex = 0;
        int shiftValue = _currentSpec.OriginalUnderlyingType switch
        {
            "ulong" or "long" => 56,
            "uint" or "int" => 24,
            "ushort" or "short" => 8,
            _ => 0
        };

        if (shiftValue != 0)
        {
            for (; shiftValue >= 0; shiftValue -= 8)
            {
                sb.Append(methodBodyIndent).Append("ToCharsBuffer((global::System.Byte)");
                if (shiftValue >= 8)
                {
                    sb.Append("(value >> ").Append(shiftValue).Append(')');
                }
                else
                {
                    sb.Append("value");
                }

                sb.Append(", destination, ").Append(startIndex).AppendLine(");");

                startIndex += 2;
            }
        }
        else
        {
            sb
                .Append(methodBodyIndent).Append("ToCharsBuffer((")
                .Append(_currentSpec.UnderlyingType).AppendLine(")data, destination, 0);");
        }

        sb
            .AppendLine()
            .Append(methodBodyIndent).AppendLine("return new global::System.String(destination);")
            .Append(methodIndent).AppendLine("}")
            .AppendLine();

        sb
           .Append(methodIndent).Append("private static global::System.String FormatFlagNames(").Append(_currentSpec.FullName).AppendLine(" value)")
           .Append(methodIndent).AppendLine("{")
           .Append(methodBodyIndent).AppendLine("switch (value)")
           .Append(methodBodyIndent).AppendLine("{");

        foreach (EnumMemberSpec member in _currentSpec.Members)
        {
            sb.Append(nesting1Indent)
                .Append("case ").Append(_currentSpec.FullName).Append('.').Append(member.Name)
                .Append(": return nameof(").Append(_currentSpec.FullName).Append('.').Append(member.Name).AppendLine(");");
        }

        sb
            .Append(nesting1Indent).AppendLine("default: return WriteMultipleFoundFlagsNames(value);")
            .Append(methodBodyIndent).AppendLine("}")
            .Append(methodIndent).AppendLine("}")
            .AppendLine()
            .Append(methodIndent)
                .Append("private static global::System.String WriteMultipleFoundFlagsNames(")
                .Append(_currentSpec.FullName).AppendLine(" value)")
            .Append(methodIndent).AppendLine("{")
            .Append(methodBodyIndent)
                .Append(_currentSpec.UnderlyingType)
                .Append(" resultValue = ");

        AddCast(sb, _currentSpec.FullName, _currentSpec.UnderlyingType)
            .AppendLine(";")
            .Append(methodBodyIndent).AppendLine("global::System.Int32 index = 0;")
            .AppendLine()
            .Append(methodBodyIndent).AppendLine("global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder();")
            .Append(methodBodyIndent).AppendLine("while (index < _underlyingValues.Length)")
            .Append(methodBodyIndent).AppendLine("{")
            .Append(nesting1Indent).Append(_currentSpec.UnderlyingType).AppendLine(" currentValue = _underlyingValues[index];")
            .Append(nesting1Indent).AppendLine("if (currentValue != 0 && (resultValue & currentValue) == currentValue)")
            .Append(nesting1Indent).AppendLine("{")
            .Append(nesting2Indent).AddCorrectBitwiseOperation(_currentSpec.OriginalUnderlyingType)
            .Append(nesting2Indent).AppendLine("sb.Append(GetSingleFlagsEnumNameForValue(currentValue));")
            .AppendLine()
            .Append(nesting2Indent).AppendLine("if (resultValue == 0) break;")
            .Append(nesting2Indent).AppendLine("sb.Append(\", \");")
            .Append(nesting1Indent).AppendLine("}")
            .AppendLine()
            .Append(nesting1Indent).AppendLine("index++;")
            .Append(methodBodyIndent).AppendLine("}")
            .AppendLine()
            .Append(methodBodyIndent).AppendLine("return sb.ToString();")
            .Append(methodIndent).AppendLine("}")
            .AppendLine()
            .Append(methodIndent)
                .Append("private static global::System.String GetSingleFlagsEnumNameForValue(")
                .Append(_currentSpec.UnderlyingType).AppendLine(" resultValue)")
            .Append(methodIndent).AppendLine("{")
            .Append(methodBodyIndent).AppendLine("switch (resultValue)")
            .Append(methodBodyIndent).AppendLine("{");

        foreach (EnumMemberSpec member in _currentSpec.Members)
        {
            sb
                .Append(nesting1Indent).Append("case ").Append(member.Value)
                .Append(": return nameof(").Append(_currentSpec.FullName).Append('.')
                .Append(member.Name).AppendLine(");");
        }

        sb
            .Append(nesting1Indent).AppendLine("default: throw CreateUnreachableException(resultValue);")
            .Append(methodBodyIndent).AppendLine("}")
            .Append(methodIndent).AppendLine("}")
            .AppendLine()
            .Append(methodIndent).AppendLine("[global::System.Security.SecuritySafeCriticalAttribute, global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]")
            .Append(methodIndent);

        AddToCharsBufferDefinition(sb);

        sb
            .Append(methodIndent).AppendLine("{")
            .Append(methodBodyIndent).AppendLine("global::System.UInt32 difference = ((value & 0xF0U) << 4) + (value & 0x0FU) - 0x8989U;")
            .Append(methodBodyIndent).AppendLine("global::System.UInt32 packedResult = ((((global::System.UInt32)(-(global::System.Int32)difference & 0x7070U)) >> 4) + difference + 0xB9B9U) | 0U;")
            .AppendLine()
            .Append(methodBodyIndent).AppendLine("buffer[startingIndex + 1] = (global::System.Char)(packedResult & 0xFFU);")
            .Append(methodBodyIndent).AppendLine("buffer[startingIndex] = (global::System.Char)(packedResult >> 8);")
            .Append(methodIndent).AppendLine("}")
            .AppendLine()
            .Append(methodIndent).AppendLine("[global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)] // https://github.com/dotnet/runtime/issues/78300")
            .Append(methodIndent).AppendLine("private static global::System.FormatException CreateInvalidFormatSpecifierException() =>")
            .Append(methodBodyIndent).AppendLine("new global::System.FormatException(\"Format string can be only \\\"G\\\", \\\"g\\\", \\\"X\\\", \\\"x\\\", \\\"F\\\", \\\"f\\\", \\\"D\\\" or \\\"d\\\".\");")
            .AppendLine()
            .Append(methodIndent).AppendLine("[global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)] // https://github.com/dotnet/runtime/issues/78300")
            .AppendLine("#if NET7_0_OR_GREATER")
            .Append(methodIndent).AppendLine("private static global::System.Diagnostics.UnreachableException CreateUnreachableException(global::System.Int32 value) =>")
            .Append(methodBodyIndent).AppendLine("new global::System.Diagnostics.UnreachableException($\"Tried to access a non-existent value: {value}\");")
            .AppendLine("#else")
            .Append(methodIndent).AppendLine("private static global::System.IndexOutOfRangeException CreateUnreachableException(global::System.Int32 value) =>")
            .Append(methodBodyIndent).AppendLine("new global::System.IndexOutOfRangeException($\"Tried to access a non-existent value: {value}\");")
            .AppendLine("#endif");
    }

    private void CloseClassAndNamespace(StringBuilder sb)
    {
        string indent = Get(Indentation.Class);
        sb
            .Append(indent)
            .AppendLine("}");

        if (!_currentSpec.IsGlobalNamespace)
        {
            sb.Append('}');
        }
    }

    private void AddSource(string fileName, string generatedClass)
    {
        _sourceGenerationContext.AddSource(fileName, SourceText.From(generatedClass, Encoding.UTF8));
    }

    protected abstract StringBuilder AddCast(StringBuilder sb, string enumName, string underlyingType);
    
    protected string Get(Indentation indentation)
    {
        if (_currentSpec.IsGlobalNamespace && indentation != Indentation.Namespace)
        {
            indentation--;
        }

        // 4 spaces per indentation.
        return indentation switch
        {
            Indentation.Class => "    ",
            Indentation.Method => "        ",
            Indentation.MethodBody => "            ",
            Indentation.Nesting1 => "                ",
            Indentation.Nesting2 => "                    ",
            Indentation.Nesting3 => "                        ",
            Indentation.Nesting4 => "                            ",
            _ => "", // Indentation.Namespace
        };
    }
}