//HintName: FastEnumExtensionsAttribute.g.cs
// <auto-generated/>

namespace FastEnum
{
    /// <summary>Marks an enum to generate optimized extensions for it.</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("FastEnum.Extensions.Generator.EnumExtensionsGenerator", "1.4.0")]
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    internal sealed class ExtensionsAttribute : global::System.Attribute { }
}