//HintName: EmptyEnumExtensions.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

namespace SnapshotTesting;

/// <summary>
/// Extension methods for <see cref="SnapshotTesting.EmptyEnum" />
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("FastEnum.Extensions.Generator.EnumExtensionsGenerator", "1.4.0")]
public static class EmptyEnumExtensions
{
    // There is no member defined for this enum.
}
