//HintName: FastEnumExtensionsAttribute.g.cs
// <auto-generated/>

namespace FastEnum
{
    /// <summary>Marks an enum to generate optimized extensions for it.</summary>
    [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    internal sealed class ExtensionsAttribute : global::System.Attribute;
}