//HintName: FastEnumExtensionsAttribute.g.cs
// <auto-generated/>

namespace FastEnum
{
    /// <summary>Marks an enum to generate optimized extensions for it.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("FastEnum.Helpers.Generator.EnumExtensionsGenerator", "1.3.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    internal sealed class ExtensionsAttribute : global::System.Attribute { }
}