//HintName: ColorExtensions.g.cs
// <auto-generated/>

#if NETCOREAPP3_0_OR_GREATER
#nullable enable annotations
#nullable disable warnings
#endif

namespace SnapshotTesting
{
    /// <summary>
    /// Extension methods for <see cref="SnapshotTesting.Color" />
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("FastEnum.Extensions.Generator.EnumToStringGenerator", "1.0.0")]
    public static class ColorExtensions
    {
        private static readonly global::System.Int32[] _underlyingValues =
        {
            0,
            1,
            2,
        };

        private static readonly SnapshotTesting.Color[] _values =
        {
            SnapshotTesting.Color.Red,
            SnapshotTesting.Color.Green,
            SnapshotTesting.Color.Blue,
        };

        private static readonly global::System.String[] _names =
        {
            nameof(SnapshotTesting.Color.Red),
            nameof(SnapshotTesting.Color.Green),
            nameof(SnapshotTesting.Color.Blue),
        };

        /// <summary>
        /// The number of members in the enum.
        /// </summary>
        public const global::System.Int32 MembersCount = 3;

        /// <summary>
        /// Retrieves an array of the values of the members defined in <see cref="SnapshotTesting.Color" />.
        /// </summary>
        /// <returns>An array of the values defined in <see cref="SnapshotTesting.Color" />.</returns>
        public static SnapshotTesting.Color[] GetValues() => _values;

        /// <summary>
        /// Retrieves an array of the underlying vales of the members defined in <see cref="SnapshotTesting.Color" />.
        /// </summary>
        /// <returns>An array of the underlying values defined in <see cref="SnapshotTesting.Color" />.</returns>
        public static global::System.Int32[] GetUnderlyingValues() => _underlyingValues;

        /// <summary>
        /// Retrieves an array of the names of the members defined in <see cref="SnapshotTesting.Color" />.
        /// </summary>
        /// <returns>An array of the names of the members defined in <see cref="SnapshotTesting.Color" />.</returns>
        public static global::System.String[] GetNames() => _names;

        /// <summary>
        /// Converts the value of this instance to its equivalent string representation.
        /// </summary>
        /// <returns>The string representation of the value of this instance.</returns>
        public static global::System.String FastToString(this SnapshotTesting.Color value) 
        {
            switch (value)
            {
                case SnapshotTesting.Color.Red: return nameof(SnapshotTesting.Color.Red);
                case SnapshotTesting.Color.Green: return nameof(SnapshotTesting.Color.Green);
                case SnapshotTesting.Color.Blue: return nameof(SnapshotTesting.Color.Blue);
                default: return ((global::System.Int32)value).ToString();
            }
        }

        /// <summary>
        /// Converts the value of this instance to its equivalent string representation using the specified format.
        /// </summary>
        /// <param name="format"> A format string.</param>
        /// <returns>The string representation of the value of this instance as specified by format.</returns>
        /// <exception cref="global::System.FormatException"><paramref name="format"/> contains an invalid specification.</exception>
        public static global::System.String FastToString(this SnapshotTesting.Color value, global::System.String format)
        {
            if (global::System.String.IsNullOrEmpty(format))
            {
                return value.FastToString();
            }

            if (format.Length != 1) throw CreateInvalidFormatSpecifierException();
            global::System.Char formatChar = format[0];
            switch (formatChar | 0x20)
            {
                case 'g': return value.FastToString();
                case 'd': return ((global::System.Int32)value).ToString();
                case 'x': return FormatNumberAsHex(value);
                case 'f': return FormatFlagNames(value);
                default: throw CreateInvalidFormatSpecifierException();
            };
        }

        /// <summary>
        /// Returns a <see langword="bool"/> telling whether the given enum value exists in the enumeration.
        /// </summary>
        /// <param name="value">The value to check if it's defined</param>
        /// <returns><see langword="true"/> if the value exists in the enumeration, <see langword="false"/> otherwise</returns>
        public static global::System.Boolean IsDefined(this SnapshotTesting.Color value)
        {
            switch (value)
            {
                case SnapshotTesting.Color.Red:
                case SnapshotTesting.Color.Green:
                case SnapshotTesting.Color.Blue:
                    return true;
                default:
                    return false;
            }
        }

        /// <summary>
        /// Formats the data for the underlying value as hex into a new, fixed-length string.
        /// </summary>
        [global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static global::System.String FormatNumberAsHex(SnapshotTesting.Color data)
        {
            global::System.Char[] destination = new global::System.Char[sizeof(global::System.Int32) * 2];
            global::System.Int32 value = (global::System.Int32)data;
            ToCharsBuffer((global::System.Byte)(value >> 24), destination, 0);
            ToCharsBuffer((global::System.Byte)(value >> 16), destination, 2);
            ToCharsBuffer((global::System.Byte)(value >> 8), destination, 4);
            ToCharsBuffer((global::System.Byte)value, destination, 6);

            return new global::System.String(destination);
        }

        private static global::System.String FormatFlagNames(SnapshotTesting.Color value)
        {
            switch (value)
            {
                case SnapshotTesting.Color.Red: return nameof(SnapshotTesting.Color.Red);
                case SnapshotTesting.Color.Green: return nameof(SnapshotTesting.Color.Green);
                case SnapshotTesting.Color.Blue: return nameof(SnapshotTesting.Color.Blue);
                default: return WriteMultipleFoundFlagsNames(value);
            }
        }

        private static global::System.String WriteMultipleFoundFlagsNames(SnapshotTesting.Color value)
        {
            global::System.Int32 resultValue = (global::System.Int32)value;
            global::System.Int32 index = 0;

            global::System.Text.StringBuilder sb = new global::System.Text.StringBuilder();
            while (index < _underlyingValues.Length)
            {
                global::System.Int32 currentValue = _underlyingValues[index];
                if (currentValue != 0 && (resultValue & currentValue) == currentValue)
                {
                    resultValue &= ~currentValue;
                    sb.Append(GetSingleFlagsEnumNameForValue(currentValue));

                    if (resultValue == 0) break;
                    sb.Append(", ");
                }

                index++;
            }

            return sb.ToString();
        }

        private static global::System.String GetSingleFlagsEnumNameForValue(global::System.Int32 resultValue)
        {
            switch (resultValue)
            {
                case 0: return nameof(SnapshotTesting.Color.Red);
                case 1: return nameof(SnapshotTesting.Color.Green);
                case 2: return nameof(SnapshotTesting.Color.Blue);
                default: throw CreateUnreachableException(resultValue);
            }
        }

        [global::System.Security.SecuritySafeCriticalAttribute, global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static void ToCharsBuffer(global::System.Byte value, global::System.Char[] buffer, global::System.Int32 startingIndex)
        {
            global::System.UInt32 difference = ((value & 0xF0U) << 4) + (value & 0x0FU) - 0x8989U;
            global::System.UInt32 packedResult = ((((global::System.UInt32)(-(global::System.Int32)difference & 0x7070U)) >> 4) + difference + 0xB9B9U) | 0U;

            buffer[startingIndex + 1] = (global::System.Char)(packedResult & 0xFFU);
            buffer[startingIndex] = (global::System.Char)(packedResult >> 8);
        }

        [global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)] // https://github.com/dotnet/runtime/issues/78300
        private static global::System.FormatException CreateInvalidFormatSpecifierException() =>
            new global::System.FormatException("Format string can be only \"G\", \"g\", \"X\", \"x\", \"F\", \"f\", \"D\" or \"d\".");

        [global::System.Runtime.CompilerServices.MethodImplAttribute(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)] // https://github.com/dotnet/runtime/issues/78300
#if NET7_0_OR_GREATER
        private static global::System.Diagnostics.UnreachableException CreateUnreachableException(global::System.Int32 value) =>
            new global::System.Diagnostics.UnreachableException($"Tried to access a non-existent value: {value}");
#else
        private static global::System.IndexOutOfRangeException CreateUnreachableException(global::System.Int32 value) =>
            new global::System.IndexOutOfRangeException($"Tried to access a non-existent value: {value}");
#endif
    }
}